### PR TITLE
regenerate rust client

### PR DESCRIPTION
**Pull request by rajatjindal**

### CODE REVIEW

**Comment by bacongobbler** [comment]
There are a few changes pending upstream; Can we hold off on regenerating this until those are complete?

CC @kate-goldenring

**Comment by rajatjindal** [comment]
yes sure, not "today" urgent. we can do this next week

**Comment by kate-goldenring** [comment]
@rajatjindal can you regenerate with the latest API updates to bring in latest variables changes?

**Review by kate-goldenring — APPROVED** [review]

**Comment by rajatjindal** [comment]
thank you @kate-goldenring for taking it to completion.

**Pull request merged**
